name: Build&Deploy
 
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download pharo
      run: wget -O- https://get.pharo.org/64/stable+vm | bash
    - name: Build image
      run: ./pharo Pharo.image metacello install filetree://. BaselineOfPhlogAWSLambda --groups=post
    - name: create bootstrap
      run: |
        echo -e '#!/bin/sh\n./pharo Pharo.image --no-default-preferences PhlogLambdaPost start' > bootstrap
        chmod +x bootstrap 
    - name: zip
      run: zip -r function.zip *.image *.changes *.sources pharo pharo-vm bootstrap
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: function
        path: function.zip
    - name: AWS Lambda Deploy
      uses: stcalica/update-lambda@0.0.2
      with:
        package: function.zip
        function-name: PhlogLambdaPost
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    
